name: go

on: [push, pull_request]

jobs:

	build:
		runs-on: ubuntu-latest
		steps:
			- name: Check out code
			  uses: actions/checkout@v3

			- name: Set up Go
				uses: actions/setup-go@v4
      	with:
					go-version: 1.20

			- name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

			- name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
