name: go

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.13'

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: gofmt -s -w . && git diff --exit-code

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: go vet ./...

  test:
    strategy:
      matrix:
        version: ['1.3', '1.4', '1.5', '1.6', '1.7',' 1.8', '1.9',' 2.0']
        os: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - run: go test -v ./...
